### ISSUE TITLE
Save posts as yaml

### ISSUE THREAD

**Issue by SRechenberger** [SRechenberger/pi-board#4]
Think about saving posts in yaml format, to have it easier formatting the output.
```yaml
title: This is a very interesting post
body:
  section:
    title: section 1
    body:
      - paragraph: >
          This is the first paragraph of this post
      - paragraph : >
          This is the second paragraph
```
should translate into
```html
<h1>This is a very interesting post</h1>
<div class="post-body">
  <h2>Section1</h2>
  <div class="section-body">
    <p>This is the first paragraph of this post</p>
    <p>This is the second paragraph of this post</p>
  </div>
</div>
```
And renders somewhat like

<h1>This is a very interesting post</h1>
<div class="post-body">
  <h2>Section1</h2>
  <div class="section-body">
    <p>This is the first paragraph of this post</p>
    <p>This is the second paragraph of this post</p>
  </div>
</div>
